Module 8
trr0jan/JavaScript-learning pull request #4
Opened 2024-06-25 11:00 UTC by trr0jan

2024-07-03 16:42 UTC, nikolas77380 requested changes

2024-07-03 16:42 UTC, nikolas77380 commented on js/app.js
> +    return parseInt(number.toString().split("").reverse().join(""));
Тут немає калькуляцій тож завжди буде інт значення - parseInt не потрібен

2024-07-03 16:42 UTC, nikolas77380 commented on js/app.js
> +    return workers.reduce((prev, current) => (current.salary > prev.salary) ? current : prev);
Ми ж вже розібрали цю задачу, чому не зробив?

2024-07-04 07:06 UTC, closed without merging

2024-07-04 07:06 UTC, trr0jan commented on js/app.js
> +    return workers.reduce((prev, current) => (current.salary > prev.salary) ? current : prev);
Вибачте, зовсім забув про 6 завдання, зараз виправлю